[package]
name = "gliding-uva-report"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Henry Zwart <@henry-zwart>"]
license = "MIT"
description = "An unofficial template for student reports at the University of Amsterdam"
repository = "https://github.com/henry-zwart/gliding-uva-report"
keywords = ["report", "university", "student"]
categories = ["report", "paper"]
compiler = "0.12.0"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
