[package]
name = "uva-report-unofficial"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Henry Zwart <@henry-zwart>"]
license = "MIT"
description = "An unofficial template for student lab reports at the University of Amsterdam"