[package]
name = "uva-report-unofficial"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Henry Zwart <@henry-zwart>"]
license = "MIT"
description = "Unofficial template for student reports at the University of Amsterdam"
repository = "https://github.com/henry-zwart/uva-report-unofficial"
keywords = ["report", "university", "student"]
categories = ["report", "paper"]
compiler = "0.12.0"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
